


export const SORT_COLORS = "SORT_COLORS";
export const ADD_COLOR = "ADD_COLOR";
export const RATE_COLOR = "RATE_COLOR";
export const REMOVE_COLOR = "REMOVE_COLOR";
export const LOGIN_USER_SUCCESSFUL = "LOGIN_USER_SUCCESSFUL";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const REGISTER_USER_SUCCESSFUL = "REGISTER_USER_SUCCESSFUL";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const GET_NUMBER_OF_PLATES = "GET_NUMBER_OF_PLATES";
export const GET_KITCHENS_LIST_FAILED = "GET_KITCHENS_LIST_FAILED";
export const GET_KITCHENS_LIST = "GET_KITCHENS_LIST";
export const GET_PLATES_LIST = "GET_PLATES_LIST";
export const GET_PLATES_LIST_FAILED = "GET_PLATES_LIST_FAILED";
export const DELETED_PLATE = "DELETED_PLATE";
export const DELETE_PLATE_FAILED = "DELETE_PLATE_FAILED";
export const LOGOUT_USER_SUCCESSFUL = "LOGOUT_USER_SUCCESSFUL";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
export const UPDATE_PROFILE_SUCCESSFUL = "UPDATE_PROFILE_SUCCESSFUL";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";
export const CLEAR_PLATE = "CLEAR_PLATE";
export const INCREMENT_ORDERS = "INCREMENT_ORDERS";

